name: Build & Publish WebSocket Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃합니다
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정 (멀티플랫폼 지원)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 도커 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/image-converter-websocket:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/image-converter-websocket:${{ github.run_number }}
